modules:
  balance:
    name: balance_wei
    type: hex
    method: eth_getBalance
    params: ["address", "block"]
  gas:
    name: geth_wei
    type: hex
    method: eth_gasPrice
  account:
    name: block
    type: hex
    method: eth_blockNumber