name: Build and Deploy
on:
  push:
    branches:
      - main
    tags:
      - v*
jobs:
  build:
    uses: NaturalSelectionLabs/Daedalus/.github/workflows/docker-tpl.yaml@main
    with:
      images: rss3/geth-exporter
      context: .
      dockerfile: ./Dockerfile
      platforms: linux/amd64,linux/arm64
    secrets: inherit